// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDmdCUtjCz84WDmo0MuHo5xISJy_35TLrE',
    appId: '1:250817358322:web:14276a22b5ecb88537a36b',
    messagingSenderId: '250817358322',
    projectId: 'e-book-store-6630e',
    authDomain: 'e-book-store-6630e.firebaseapp.com',
    storageBucket: 'e-book-store-6630e.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAVmWk5TXKSNeVGSgGRQpuCfhMuhRMBP3U',
    appId: '1:250817358322:android:4d760f11d44f011c37a36b',
    messagingSenderId: '250817358322',
    projectId: 'e-book-store-6630e',
    storageBucket: 'e-book-store-6630e.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAQWb3S3bN-4tMCWW9G4DdHVJs-BP0dTyk',
    appId: '1:250817358322:ios:9cb9148f77ccbe5537a36b',
    messagingSenderId: '250817358322',
    projectId: 'e-book-store-6630e',
    storageBucket: 'e-book-store-6630e.appspot.com',
    iosBundleId: 'com.example.bookFlutter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAQWb3S3bN-4tMCWW9G4DdHVJs-BP0dTyk',
    appId: '1:250817358322:ios:9cb9148f77ccbe5537a36b',
    messagingSenderId: '250817358322',
    projectId: 'e-book-store-6630e',
    storageBucket: 'e-book-store-6630e.appspot.com',
    iosBundleId: 'com.example.bookFlutter',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDmdCUtjCz84WDmo0MuHo5xISJy_35TLrE',
    appId: '1:250817358322:web:fd0f9bc831025c0337a36b',
    messagingSenderId: '250817358322',
    projectId: 'e-book-store-6630e',
    authDomain: 'e-book-store-6630e.firebaseapp.com',
    storageBucket: 'e-book-store-6630e.appspot.com',
  );
}
